### ISSUE TITLE
typo in shader compilation

### ISSUE THREAD

**Issue by MrROBUST** [rdunnington/d3d12-hello-triangle#2]
https://github.com/rdunnington/d3d12-hello-triangle/blob/ff15da8b8f5e1bdcc18831bbd388f8034784d1f6/main.c#L475
It's a typo? It looks like this message should be related to the pixel shader, not the vertex shader.

**Comment by rdunnington** [comment]
Yes, thanks for the report. Should be closed with 41b5b66.
